#!/bin/sh

# PROVIDE: upercoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# upercoin_enable (bool): Set to NO by default. Set this variable to YES if you want to enable upercoin service.
# upercoin_config (path): Set to /usr/local/etc/upercoin.conf by default.
# upercoin_user:  The user account upercoin daemon runs as. It uses 'root' user by default.
# upercoin_group: The group account upercoin daemon runs as. It uses 'wheel' group by default.
# upercoin_datadir (str): Default to "/var/db/upercoin". Base data directory.

. /etc/rc.subr

name=upercoin
rcvar=upercoin_enable

: ${upercoin_enable:=NO}
: ${upercoin_config=/usr/local/etc/upercoin.conf}
: ${upercoin_datadir=/var/db/upercoin}
: ${upercoin_user="root"}
: ${upercoin_group="wheel"}

required_files=${upercoin_config}
command=/usr/local/bin/upercoind
upercoin_chdir=${upercoin_datadir}
pidfile="${upercoin_datadir}/upercoind.pid"
stop_cmd=upercoin_stop
command_args="-conf=${upercoin_config} -datadir=${upercoin_datadir} -noupnp -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

upercoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${upercoin_datadir}
	[ $? -eq 0 ] && chown -R ${upercoin_user}:${upercoin_group} ${upercoin_datadir}
}

upercoin_prestart()
{
	if [ ! -d "${upercoin_datadir}/." ]; then
		upercoin_create_datadir || return 1
	fi
}

upercoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

upercoin_stop()
{
    upercoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${upercoin_config} -datadir=${upercoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
